set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_C_COMPILER arm-cortex_a8-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER arm-cortex_a8-linux-gnueabihf-g++)
set(CMAKE_SYSROOT /home/ruvinda/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot)
